//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cg.Tests.IntegrationTests.TestFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cg.Tests.IntegrationTests.TestFiles.InputResources", typeof(InputResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:10.00, &quot;quantity&quot;: 100},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:15.00, &quot;quantity&quot;: 50},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:15.00, &quot;quantity&quot;: 50}].
        /// </summary>
        internal static string case1 {
            get {
                return ResourceManager.GetString("case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:10.00, &quot;quantity&quot;: 10000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:20.00, &quot;quantity&quot;: 5000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:5.00, &quot;quantity&quot;: 5000}].
        /// </summary>
        internal static string case2 {
            get {
                return ResourceManager.GetString("case2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:10.00, &quot;quantity&quot;: 10000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:5.00, &quot;quantity&quot;: 5000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:20.00, &quot;quantity&quot;: 3000}].
        /// </summary>
        internal static string case3 {
            get {
                return ResourceManager.GetString("case3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:10.00, &quot;quantity&quot;: 10000},{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:25.00, &quot;quantity&quot;: 5000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:15.00, &quot;quantity&quot;: 10000}].
        /// </summary>
        internal static string case4 {
            get {
                return ResourceManager.GetString("case4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:10.00, &quot;quantity&quot;: 10000},{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:25.00, &quot;quantity&quot;: 5000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:15.00, &quot;quantity&quot;: 10000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:25.00, &quot;quantity&quot;: 5000}].
        /// </summary>
        internal static string case5 {
            get {
                return ResourceManager.GetString("case5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:10.00, &quot;quantity&quot;: 10000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:2.00, &quot;quantity&quot;: 5000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:20.00, &quot;quantity&quot;: 2000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:20.00, &quot;quantity&quot;: 2000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:25.00, &quot;quantity&quot;: 1000}].
        /// </summary>
        internal static string case6 {
            get {
                return ResourceManager.GetString("case6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:10.00, &quot;quantity&quot;: 10000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:2.00, &quot;quantity&quot;: 5000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:20.00, &quot;quantity&quot;: 2000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:20.00, &quot;quantity&quot;: 2000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:25.00, &quot;quantity&quot;: 1000},{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:20.00, &quot;quantity&quot;: 10000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:15.00, &quot;quantity&quot;: 5000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:30.00, &quot;quantity&quot;: 4350},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:30.00, &quot;quantit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string case7 {
            get {
                return ResourceManager.GetString("case7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:10.00, &quot;quantity&quot;: 10000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:50.00, &quot;quantity&quot;: 10000},{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:20.00, &quot;quantity&quot;: 10000},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:50.00, &quot;quantity&quot;: 10000}].
        /// </summary>
        internal static string case8 {
            get {
                return ResourceManager.GetString("case8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:  5000.00, &quot;quantity&quot;:  10},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:  4000.00, &quot;quantity&quot;:5},{&quot;operation&quot;:&quot;buy&quot;,  &quot;unit-cost&quot;: 15000.00, &quot;quantity&quot;:5},{&quot;operation&quot;:&quot;buy&quot;,  &quot;unit-cost&quot;:  4000.00, &quot;quantity&quot;:   2},{&quot;operation&quot;:&quot;buy&quot;,  &quot;unit-cost&quot;: 23000.00, &quot;quantity&quot;:   2},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;: 20000.00, &quot;quantity&quot;:   1},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;: 12000.00, &quot;quantity&quot;:  10},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;: 15000.00, &quot;quantity&quot;:   3}].
        /// </summary>
        internal static string case9 {
            get {
                return ResourceManager.GetString("case9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:10.00, &quot;quantity&quot;: 100},{&quot;operation&quot;:&quot;change&quot;, &quot;unit-cost&quot;:15.00, &quot;quantity&quot;: 150}].
        /// </summary>
        internal static string caseInvalidOperation {
            get {
                return ResourceManager.GetString("caseInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;operation&quot;:&quot;buy&quot;, &quot;unit-cost&quot;:10.00, &quot;quantity&quot;: 100},{&quot;operation&quot;:&quot;sell&quot;, &quot;unit-cost&quot;:15.00, &quot;quantity&quot;: 150}].
        /// </summary>
        internal static string caseOutOfStock {
            get {
                return ResourceManager.GetString("caseOutOfStock", resourceCulture);
            }
        }
    }
}
