//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cg.Tests.IntegrationTests.TestFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OutputResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OutputResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cg.Tests.IntegrationTests.TestFiles.OutputResources", typeof(OutputResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0}].
        /// </summary>
        internal static string case1 {
            get {
                return ResourceManager.GetString("case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 10000.0},{&quot;tax&quot;: 0.0}].
        /// </summary>
        internal static string case2 {
            get {
                return ResourceManager.GetString("case2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 1000.0}].
        /// </summary>
        internal static string case3 {
            get {
                return ResourceManager.GetString("case3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0}].
        /// </summary>
        internal static string case4 {
            get {
                return ResourceManager.GetString("case4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 10000.0}].
        /// </summary>
        internal static string case5 {
            get {
                return ResourceManager.GetString("case5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 3000.0}].
        /// </summary>
        internal static string case6 {
            get {
                return ResourceManager.GetString("case6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 3000.0}, {&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 3700.0},{&quot;tax&quot;: 0.0}].
        /// </summary>
        internal static string case7 {
            get {
                return ResourceManager.GetString("case7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 80000.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 60000.0}].
        /// </summary>
        internal static string case8 {
            get {
                return ResourceManager.GetString("case8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 0.0},{&quot;tax&quot;: 1000.0},{&quot;tax&quot;: 2400.0}].
        /// </summary>
        internal static string case9 {
            get {
                return ResourceManager.GetString("case9", resourceCulture);
            }
        }
    }
}
