name: build-test
on: push
jobs:

  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure .Net8
        uses: actions/setup-dotnet@v4
        with: 
            dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build projects
        run: dotnet build --no-restore

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CG-Artifact
          path: |
            Capital-Gains-Project/Cg.Console/bin/Debug/net8.0

  
  
        


